name: "Dependency-Check"

on: push

jobs:
  Dependency-check:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'test'
        path: '.'
        format: 'HTML'

    - name: Upload test result
      uses: actions/upload-artifact@v2
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports
