name: Heroku Deployment

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Heroku Login
        run: |
          heroku container:login
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Heroku Push
        run: |
          heroku container:push web -a spike-saas
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Heroku Release
        run: |
          heroku container:release web -a spike-saas
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Discord WebHook Test
        uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          nodetail: true
          title: "Spike-SaaS Successfully Deployed"
          color: 0xff91a4