name: Zap Scan

on: push

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Zap Scan
      uses: zaproxy/action-baseline@v0.6.1
      with:
        target: 'https://spike-saas.herokuapp.com/'

